### ISSUE TITLE
[request] add option to open http proxy as well as socks5 using HTTPTunnelPort

### ISSUE THREAD

**Issue by junguler** [abysshint/tor-control-panel#2]
hi again, sorry for opening another issue back to back, i really enjoy using your program but i found it's missing a feature i really like and that's opening a http proxy using `HTTPTunnelPort` in torrc, somthing like this `HTTPTunnelPort 9080`

i use tor for censorship circumvention, mainly watching youtube videos, both mpv and ffmpeg don't support socks5 proxies so i use the http proxy for those cases

thanks again for your amazing program

**Comment by abysshint** [comment]
I took a note, I think this will be implemented in the next version, but for now you can manually add HTTPTunnelPort to the torrc file.

**Comment by junguler** [comment]
thank you, it worked

**Comment by abysshint** [comment]
Implemented in v2.2.11.12

**Comment by junguler** [comment]
thanks
