### ISSUE TITLE
Error dialog when trying to stop or start Tor from the tray

### ISSUE THREAD

**Issue by Dhowti** [abysshint/tor-control-panel#3]
Subj. Screenshot attached.
Win 11 22H2 Russian.
![Снимок экрана 2022-11-18 104801](https://user-images.githubusercontent.com/108597329/202591186-08998fa9-759b-485c-87b9-4bf871673fcc.jpg)

**Comment by abysshint** [comment]
Bug Fixed in https://github.com/abysshint/tor-control-panel/commit/2b65849b52685dd7086b73bccc69c6415e720fac
