### ISSUE TITLE
[request] proxychain

### ISSUE THREAD

**Issue by ignisRegulus** [abysshint/tor-control-panel#4]
Hello, would you ever consider adding the proxychain functionality? I think it would increase the chances of security. Thanks.

**Comment by abysshint** [comment]
TCP is the GUI for Tor. Tor does not provide the ability to implement proxy chains. TCP does not handle traffic and as a result cannot redirect it to other proxy servers. To create proxy chains, use the [3proxy ](https://github.com/3proxy/3proxy) or [proxifier ](https://proxifier.com/) programs
