### ISSUE TITLE
virus detected!

### ISSUE THREAD

**Issue by 9px** [abysshint/tor-control-panel#6]
hi. i upload the released exe file to virustotal and i get alert from 14 antivirus:
https://www.virustotal.com/gui/file/e7179adcf6ea092ddf18b866b90ca538bd9eb9ead7be00fbef2b790fa0ef7201

**Comment by abysshint** [comment]
These are false positives from little-known antivirus scanners, this is normal.

I changed the SFX module, the number of false positives [decreased](https://www.virustotal.com/gui/file/90cba6c722b395081a31ed0c6a7579bc002b374e9cfd183b75dcda8218aab8ba). The installer files have been updated.
