### ISSUE TITLE
Add support for using NT service

### ISSUE THREAD

**Issue by DemonikGH** [abysshint/tor-control-panel#8]
I configured Tor expert bundle myself to run as NT service and have been using it for a while but this project doesn't seem to have a way to connect to it. Currently I'm using ipython console to control it but it'd be nice to be able to control it with GUI and this seems to be the only windows GUI project that I found.

**Comment by abysshint** [comment]
The current model of tor interaction with the graphical interface does not allow you to fully manage tor, which is launched as an NT service.
 - The GUI is also a controller that monitors events through the control port. If you connect the controller some time after the launch of tor, you will not be able to get complete information about the current state of circuits, streams, traffic.
 - The data for the "Log" section comes directly from the tor process stdout. This allows you to unload the control port from a large amount of processed data. To do this, a system of Pipes is used, which are tied to the process at the stage of its creation and launch. When tor is launched as an NT service, this cannot be done.
 - Managing the tor service will require mandatory launch of the Tor Control Panel (TCP) on behalf of the Administrator.

The NT service is suitable for Tor to work as a server, when configured the torrc file once and forgot. But when you need to monitor circuits and streams in real time, change node lists and quickly synchronize all this with the GUI, the tor NT service will not be enough.

If you need TCP to start when Windows starts, then add the program shortcut to the Startup folder. It is not necessary to install tor as an NT service.
