### ISSUE TITLE
custom torrc setting

### ISSUE THREAD

**Issue by lollita** [abysshint/tor-control-panel#9]
Do it is possible to add custom setting in torrc?
When I try it delete it after apply in control panel setting.

Do you can use
.\
instead full path in torrc?

**Comment by abysshint** [comment]
Yes, you can add a custom setting to the torrc file, but the options that can be configured over TCP **will be overwritten** before starting tor **to avoid desynchronization** of settings in the GUI and the torrc file.

It is possible to use relative paths, but tor does not like them and writes messages at startup:
`[warn] Path for DataDirectory (.\Data\User) is relative and will resolve to D:\TCP\Data\User. Is this what you wanted?`

Therefore, it was decided not to use them in the torrc file. Before each launch, the paths in the torrc file are replaced with the correct ones if you moved the TCP directory to another location.

**Comment by lollita** [comment]
ExitPolicy reject *:*
is deleted
but not like as be configured over TCP.

**Comment by abysshint** [comment]
ExitPolicy is used in **Exit relay** server mode to set a **Custom** ExitPolicy
When using the **Bridge** (BridgeRelay 1) or **Relay** (ExitRelay 0) server mode, tor **automatically adds**: ExitPolicy reject \*:\*, so there is no need to add this line to the torrc file.
In client mode (tor's default mode), this setting is i**gnored and has no effect.**
